language: shell
dist: xenial
os: linux

env:
  global:
    - LC_ALL: C.UTF-8
    - LANG: C.UTF-8
    - SNAPCRAFT_ENABLE_SILENT_REPORT: y
    - SNAPCRAFT_BUILD_INFO: 1
    #- SOURCE_TAG: vX.Y.Z

addons:
  snaps:
    - name: snapcraft
      channel: stable
      confinement: classic

script:
- snapcraft --destructive-mode

after_failure:
- sudo journalctl -u snapd

deploy:
  provider: snap
  snap: travis_*.snap
  channel: stable
  cleanup: false
  skip_cleanup: true
